import './globals.css'
import { Inter, Amatic_SC, Sawarabi_Mincho  } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const amatic = Amatic_SC ({ 
  subsets:['latin'],
  weight:['400', '700'],
 
})
const sawarabi = Sawarabi_Mincho({
  subsets:['latin'],
  weight:['400']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex justify-center bg-black text-white'>
     
      <body className={amatic.className}>{children}
      
      </body>
    </html>
  )
}
